# Generated by Django 5.2.14 on 2026-05-13 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato'),
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída (Baixa)')], max_length=10, verbose_name='Tipo de Movimentação')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('telefone_contato', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato')),
                ('crm', models.CharField(blank=True, max_length=20, null=True, verbose_name='CRM')),
                ('nome_medico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Médico')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.medicamento', verbose_name='Medicamento')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
            },
        ),
    ]
