# Generated by Django 5.2.14 on 2026-05-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_relatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='quantidade_por_caixa',
            field=models.IntegerField(default=1, verbose_name='Quantidade por Caixa'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('COMPRIMIDO', 'Comprimido'), ('GOTA', 'Gota')], max_length=20, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='unidade_dosagem',
            field=models.CharField(blank=True, choices=[('MG', 'mg'), ('ML', 'ml'), ('CAPSULA', 'Cápsula')], max_length=20, null=True, verbose_name='Unidade de Dosagem'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade'),
        ),
    ]
