# Generated by Django 5.2.14 on 2026-05-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_medicamento_fabricante_medicamento_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='medicamentos_em_uso',
            field=models.TextField(blank=True, null=True, verbose_name='Medicamentos em Uso'),
        ),
    ]
