# Generated by Django 5.2.14 on 2026-05-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_paciente_medicamentos_em_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='crm_medico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CRM do Médico'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medico_prescritor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Médico Prescritor'),
        ),
    ]
