# Generated by Django 5.2.14 on 2026-05-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_paciente_crm_medico_paciente_medico_prescritor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='crm',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='nome_medico',
        ),
    ]
